# Generated by Django 2.2.19 on 2021-03-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('post_date', models.DateTimeField(editable=False)),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
