# Generated by Django 3.1.7 on 2021-03-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210303_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='edit_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
